### ISSUE TITLE
Broken install: dist/ not in node_modules when installing the npm package

### ISSUE THREAD

**Issue by mdubourg001** [willmendesneto/hex-to-css-filter#22]
### Minimal example

[CodeSandbox reproduction](https://codesandbox.io/s/silent-river-50reol?file=/src/index.js).

### Expected behaviour

When installing the lib, we should be able to import from it using `import hexToCssFilter from "hex-to-css-filter"`.

### Actual behaviour

As no bundle is shipped with the lib (`node_modules/hex-to-css-filter/dist/` doesn't exist), we are unable to use it.

### How to simulate the behaviour (if applicable)

Check out the given CodeSandbox link up here ☝️ or just `yarn add hex-to-css-filter` to any project and try to import it.

**Comment by willmendesneto** [comment]
Hi @mdubourg001 ! Thanks for raising this issue.

For some cryptic reason the dist folder wasn't shipped on the previous package publishment. So I just published a new version with the fix. Please feel free to add `hex-to-css-filter@5.3.0` in your project and enjoy!

There's a Stackblitz demo showing how it works here (https://stackblitz.com/edit/hex-to-css-filter-playground) and I also updated your codesandbox example with the fix as well https://codesandbox.io/s/busy-stallman-6xb6nb?file=/src/index.js

One note that might be good to mention: please check your code because this package doesn't have any default export for some relevant reasons (https://basarat.gitbook.io/typescript/main-1/defaultisbad), so the code in your example won't work.

Instead, you should use like the example on the `README.md` file.

```js
import { hexToCSSFilter } from 'hex-to-css-filter';

const cssFilter = hexToCSSFilter('#00a4d6');
console.log(cssFilter);
```

Closing this issue since it's solved. And, once again, thanks heaps for raising this issue!
