### ISSUE TITLE
Missing typescript declaration 

### ISSUE THREAD

**Issue by DelphLB** [willmendesneto/hex-to-css-filter#25]
### Minimal example

[Code sandbox example](https://codesandbox.io/s/infallible-flower-1miieo?file=/src/index.ts)

### Actual behaviour

Types declaration is missing even after using the command `yarn add  @types/hex-to-css-filter`

### How to simulate the behaviour (if applicable)

This is the example of the current behaviour  https://codesandbox.io/s/infallible-flower-1miieo?file=/src/index.ts

**Comment by willmendesneto** [comment]
Hi @DelphLB Thanks for raising this issue.

I just published a new version for this package with the fix and checked that's working by forking your code sandbox example.

https://codesandbox.io/s/small-tree-rdxl2n?file=/src/index.ts

Feel free to upgrade your project to use `hex-to-css-filter@5.4.0` to get the fix in your repository.

I'm closing this issue since it was solved already. Once again, thank you very much for raising this issue!
