### ISSUE TITLE
Thre is not same result on mobile and pc.

### ISSUE THREAD

**Issue by ChoWonmin** [willmendesneto/hex-to-css-filter#29]
### Minimal example

Thre is not same result on mobile and pc.

### Expected behaviour
I expected same result on mobile and pc browser.

### Actual behaviour

code: hexToCSSFilter('#4798FF')

macos chrome result: invert(46%) sepia(93%) saturate(1310%) hue-rotate(195deg) brightness(103%) contrast(100%)
ios safari result: invert(47%) sepia(99%) saturate(1304%) hue-rotate(193deg) brightness(101%) contrast(101%)

**Comment by willmendesneto** [comment]
Hi @ChoWonmin 👋  Thanks for raising this issue.

This is a known behavior based on the core of the library. That's not related to device, let me elaborate about it:

There's a `Solver` class. This class is responsible to apply all the math and return the CSS Filter value as resolution based on the hex color. In this file, all these filters are created based on `acceptanceLossPercentage` and `maxChecks`, respectively.

As soon as the value returned is acceptable, the specific filter is returned as a valid one since the final result will match with the expected loss. This is a performance decision to avoid massive checks that might result in performance degradation to get that value.

> You can find more details about Solver class in this link https://github.com/willmendesneto/hex-to-css-filter/blob/main/src/solver.ts

Saying that, I'm closing this issue. Thanks, mate!
