### ISSUE TITLE
Sometimes the filter is brighter

### ISSUE THREAD

**Issue by lighttigerXIV** [willmendesneto/hex-to-css-filter#37]
### Minimal example

Thanks for making this library. I have been using this library for some months and sometimes the filter applies the wrong color. Mostly a brighter one. Do you know if i am doing something wrong or you know a fix for this?

The code i am using:
- [To get the filter](https://github.com/lighttigerXIV/whiskers-launcher/blob/master/src/whiskers/src/utils.ts):
```typescript
export function getHexCssFilter(hexColor: string): string {
  const filter = hexToCSSFilter(hexColor);
  return filter.filter.replace(";", "");
  // return filter.filter.slice(0, -1); I have this one another project
}
```

- [To use the filter](https://github.com/lighttigerXIV/whiskers-launcher/blob/master/src/whiskers/src/pages/Search/Search.vue):
```typescript
accentPrimaryFilter.value = getHexCssFilter(theme.accent_primary);
```

I then use the variable as a filter on vue elements.

### Expected behaviour

The `hextToCssFilter` function should return the proper color filter.
The following image shows how it should return
![Screenshot 2024-03-17 150503](https://github.com/willmendesneto/hex-to-css-filter/assets/35658492/44ff0bc4-41d6-4d69-889e-13f97c50c90c)

### Actual behaviour

The `hextToCssFilter` function has a small chance that returns the wrong color filter.
You can see the following image with the wrong color filter:
![Screenshot 2024-03-17 150355](https://github.com/willmendesneto/hex-to-css-filter/assets/35658492/17a6b891-b839-4970-82a2-2a521eb3ed42)

### How to simulate the behaviour (if applicable)

It's a very slim chance of it happening but when i tried using `acceptanceLossPercentage: 0` in the options i believe it shows the error more often 

### Browsers/OS/Platforms affected

Any platform. Happens on android, linux and windows. (Can't test mac os)

**Comment by willmendesneto** [comment]
Hi @lighttigerXIV thanks for raising this issue.

Something interesting about the result is that `acceptanceLossPercentage` can't be `0` since any color manipulation might have a loss percentage. What the library does is:
- Generates CSS filters based on `maxChecks` config - default value is `30`
- If gets any result which satisfies `acceptanceLossPercentage` value, it stops the check and it returns the CSS filter values. Good to keep in mind this can happen on the first try or none of the tries.
  - If it tries the number defined on `maxChecks`, but it does not satisfy `acceptanceLossPercentage`, it returns the value closest to `acceptanceLossPercentage` defined, which is the CSS filter most similar to the color
  
This is a known issue and predefined as an arch decision. Otherwise, the lib might be running in infinite loop until gets the expected result, causing issues such as memory leak, performance degradation and such.

What I would suggest in your case is to increase `maxChecks` instead of decrease `acceptanceLossPercentage`. E.G:

```ts
import { hexToCSSFilter, HexToCssConfiguration } from 'hex-to-css-filter';

export function getHexCssFilter(hexColor: string): string {
  const config: HexToCssConfiguration = {
    acceptanceLossPercentage: 1,
    // This one is important since the default number of checks is 30
    maxChecks: 50,
  };

  const { filter } = hexToCSSFilter(hexColor, config);
  return filter.slice(0, -1); 
}
```

**Comment by lighttigerXIV** [comment]
Sorry for the late response.

So, i searched another library that did the same thing and it returned the loss values. With that i could see the acceptance percentage i truly needed.

Since i can't really use 0 as acceptance i decided to use 0.1 wich the algortithm can make it mostly up to 5 checks.

I had to make some loops and the code looked bad so i ended up getting back to this library. My final code is the following and it has been working great for me:

```typescript
export function getHexCssFilter(hexColor: string): string {
  const { filter } = hexToCSSFilter(hexColor, {
    acceptanceLossPercentage: 0.1,
    maxChecks: 50,
  });

  return filter.slice(0, -1);
}
```

You can close the issue if you want XD
